In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
zoo = pd.read_csv ('zoo.csv')
car = pd.read_csv ('car.csv')

In [5]:
zoo.head()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [6]:
zoo.dtypes

animal_name    object
hair            int64
feathers        int64
eggs            int64
milk            int64
airborne        int64
aquatic         int64
predator        int64
toothed         int64
backbone        int64
breathes        int64
venomous        int64
fins            int64
legs            int64
tail            int64
domestic        int64
catsize         int64
class_type      int64
dtype: object

In [7]:
zoo.shape

(100, 18)

In [25]:
x = zoo.iloc[:,1:17]
y = zoo.iloc[:,17:18]

In [24]:
x

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize
0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0
3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1
5,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
6,1,0,0,1,0,0,0,1,1,1,0,0,4,1,1,1
7,0,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0
8,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0
9,1,0,0,1,0,0,0,1,1,1,0,0,4,0,1,0
10,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1
11,0,1,1,0,1,0,0,0,1,1,0,0,2,1,1,0
12,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0
13,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0
14,0,0,1,0,0,1,1,0,0,0,0,0,4,0,0,0
15,0,0,1,0,0,1,1,0,0,0,0,0,6,0,0,0
16,0,1,1,0,1,0,1,0,1,1,0,0,2,1,0,0
17,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
18,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,1
19,0,0,0,1,0,1,1,1,1,1,0,1,0,1,0,1
20,0,1,1,0,1,0,0,0,1,1,0,0,2,1,1,0
21,0,1,1,0,1,1,0,0,1,1,0,0,2,1,0,0
22,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
23,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,1
24,0,0,1,0,0,0,0,0,0,1,0,0,6,0,0,0
25,0,0,1,0,0,1,1,1,1,1,0,0,4,0,0,0
26,0,0,1,0,0,1,1,1,1,1,1,0,4,0,0,0
27,1,0,0,1,1,0,0,1,1,1,0,0,2,1,0,0
28,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
29,0,0,1,0,1,0,0,0,0,1,0,0,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0,1,1,0,0,0,1,0,1,1,0,0,2,1,0,1
71,0,0,0,0,0,0,1,0,0,1,1,0,8,1,0,0
72,0,0,1,0,0,1,0,1,1,0,0,1,0,1,0,0
73,1,0,0,1,0,1,1,1,1,1,0,1,0,0,0,1
74,1,0,0,1,0,1,1,1,1,1,0,1,2,1,0,1
75,0,0,0,0,0,1,1,1,1,0,1,0,0,1,0,0
76,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0
77,0,1,1,0,1,1,1,0,1,1,0,0,2,1,0,0
78,0,1,1,0,1,1,1,0,1,1,0,0,2,1,0,0
79,0,0,1,0,0,0,1,1,1,1,0,0,0,1,0,0
80,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
81,0,0,1,0,0,1,0,1,1,0,0,1,0,1,0,0
82,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0
83,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,0
84,0,0,1,0,0,1,1,0,0,0,0,0,5,0,0,0
85,0,0,1,0,0,1,1,1,1,0,1,1,0,1,0,1
86,0,1,1,0,1,1,0,0,1,1,0,0,2,1,0,1
87,0,0,1,0,0,0,0,0,0,1,0,0,6,0,0,0
88,0,0,1,0,0,1,0,1,1,1,0,0,4,0,0,0
89,0,0,1,0,0,0,0,0,1,1,0,0,4,1,0,1
90,0,0,1,0,0,0,1,1,1,1,0,0,4,1,0,0
91,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,1
92,1,0,0,1,1,0,0,1,1,1,0,0,2,1,0,0
93,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,0
94,0,1,1,0,1,0,1,0,1,1,0,0,2,1,0,1
95,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1
96,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0
97,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1
98,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
99,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0

In [26]:
y

    class_type
0            1
1            1
2            4
3            1
4            1
5            1
6            1
7            4
8            4
9            1
10           1
11           2
12           4
13           7
14           7
15           7
16           2
17           1
18           4
19           1
20           2
21           2
22           1
23           2
24           6
25           5
26           5
27           1
28           1
29           6
..         ...
70           2
71           7
72           4
73           1
74           1
75           3
76           7
77           2
78           2
79           3
80           7
81           4
82           2
83           1
84           7
85           4
86           2
87           6
88           5
89           3
90           3
91           4
92           1
93           1
94           2
95           1
96           6
97           1
98           7
99           2

[100 rows x 1 columns]